#!/bin/sh

set -ea # Exit on Error and Export all vars

if [ -n "$DEBUG_ENTRYPOINT" ]; then
  set -x
fi

. ./conf.env

while ! nc -z "$DB_HOST" 5432; do
  echo "Waiting for PostgreSQL..."
  sleep 2
done

cd taiga-back/settings
envsubst < dockerenv.py > local.py

if [ -n "$GITHUB_API_CLIENT_ID" ]; then
  echo "GITHUB_API_CLIENT_ID = '$GITHUB_API_CLIENT_ID'" >> local.py
  echo "GITHUB_API_CLIENT_SECRET = '$GITHUB_API_CLIENT_SECRET'" >> local.py
fi

cd .. # back to taiga-back

# Allow migration to fail due to already initialized DB
{
  python manage.py migrate --noinput &&
  python manage.py loaddata initial_user &&
  python manage.py loaddata initial_project_templates &&
  python manage.py loaddata initial_role

  if [ -n "$SAMPLE_DATA" ]; then
    python manage.py sample_data
  fi
}

python manage.py compilemessages
python manage.py collectstatic --noinput

cd .. # and back to the roots

/usr/local/bin/circusd circus.ini
